"use client"

import { useContext } from 'react'
import './globals.css'
import type { Metadata } from 'next'
import { ModeContext } from '@/contexts/InputContext'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

 
  return (
    <html lang="en">
      <body className="bg-zinc-800">{children}</body>
    </html>
  )
}
